name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - .github/**
      - husky/**
      - .vscode/**
      - .docs/**
  push:
    branches:
      - master
      - develop
      - 'push-action/**'
    paths-ignore:
      - .github/**
      - husky/**
      - .vscode/**
      - .docs/**
  # workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    with:
      persist-credentials: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: pnpm audit

      - name: Publish release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
          branch: master
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: cycjimmy/semantic-release-action@v3
        # run: pnpm semantic-release
